apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ctrlmesh-mutating
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      url: https://ctrlmesh-webhook-service.ctrlmesh.svc:9443/mutate-resource
    failurePolicy: Fail
    matchPolicy: Exact
    name: mutating-resource.ctrlmesh.sofastack.io
    namespaceSelector:
      matchExpressions:
        - key: ctrlmesh.kusionstack.io/control
          operator: In
          values:
            - "true"
    objectSelector:
      matchExpressions:
        - key: ctrlmesh.kusionstack.io/ignore-webhook
          operator: DoesNotExist
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - events
        scope: Namespaced
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - persistentvolumeclaims
          - services
          - replicasets
          - endpoints
          - statefulsets
          - controllerrevisions
          - configmaps
        scope: Namespaced
      - apiGroups:
          - ctrlmesh.kusionstack.io
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
        scope: Namespaced
    sideEffects: Unknown
    timeoutSeconds: 30
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      url: https://ctrlmesh-webhook-service.ctrlmesh.svc:9443/mutate-namespace
    failurePolicy: Fail
    matchPolicy: Exact
    name: mutating-namespace.ctrlmesh.kusionstack.io
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
        - key: ctrlmesh.kusionstack.io/ignore-webhook
          operator: DoesNotExist
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - namespaces
        scope: '*'
    sideEffects: Unknown
    timeoutSeconds: 30
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      url: https://ctrlmesh-webhook-service.ctrlmesh.svc:9443/mutate-pod
    failurePolicy: Fail
    matchPolicy: Exact
    name: mutating-pod.ctrlmesh.kusionstack.io
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
        - key: ctrlmesh.kusionstack.io/inject-proxy
          operator: In
          values:
            - "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: Unknown
    timeoutSeconds: 30